[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.6.0"
itertools = "0.13.0"
nom = "7.1.3"
rayon = "1.10.0"


[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
